[workspace]
members = ["crates/riff-auth", "crates/riff-api", "crates/riff-config", "generated/spotify-api"]
resolver = "2"

[package]
name = "riff"
version = "26.7.0"
edition = "2018"
license = "MIT"

[dependencies]
riff-api = { path = "crates/riff-api" }
riff-auth = { path = "crates/riff-auth" }
serde_json = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
gio = "0.20"
glib = "0.20"
futures = "0.3.18"
ref_filter_map = "1.0.1"
zbus = "4.4.0"
zvariant = "4.2.0"
int-enum = "1.2.0"
lazy_static = "1.4.0"
log = "0.4.17"
env_logger = "0.10.0"
percent-encoding = "2.2.0"
url = "2.4.1"
open = "5.3.0"


[dependencies.gtk]
version = "^0.9"
package = "gtk4"
features = ["gnome_47", "blueprint"]

[dependencies.libadwaita]
version = "^0.7"
features = ["v1_7"]

[dependencies.gdk]
version = "^0.9"
package = "gdk4"

[dependencies.librespot]
version = "0.8.0"
features = ["alsa-backend", "pulseaudio-backend"]

[dependencies.tokio]
version = "1"
features = ["rt", "fs", "macros", "sync"]

[dependencies.rand]
version = "^0.8.5"
features = ["small_rng"]

[dependencies.gettext-rs]
version = "=0.7.0"
features = ["gettext-system"]


